### ISSUE TITLE
DVSCF vs. DVSCF1

### ISSUE THREAD

**Issue by hurricane642** [perturbo-code/perturbopy#24]
In the current version, after the phonon calculation we collect files in format `*.dvscf1`. That is not right in case of the serial version of QE (in this case, file of format `*.dvscf` would be generated. 
As a result, testsuite code breaks in case of a serialized version of QE (the Docker version, as an example). 
Changes will be made as soon as we close all the issues with renaming `epwan/epr`

**Comment by imaliyov** [comment]
Sounds reasonable! By the way, do we collect now the dvscf files with a Python function or with a bash script?

**Comment by hurricane642** [comment]
> Sounds reasonable! By the way, do we collect now the dvscf files with a Python function or with a bash script?
With the python code - i'be implemented it in the commit 41d4718

**Comment by hurricane642** [comment]
Solved in #25
